#! /bin/bash
echo "Programa Estaciones"
ruta="/var/ftp/pub"
temporal=""
variable1=""
estacion=""
IIUNAM=""
IIUNAMMESA=""
COAPA=""
COAPAMESA=""
ARAGON=""
ARAGONMESA=""
BOSQUEREAL=""
BOSQUEREALMESA=""
minActual=$(date "+%M")
min=70
number=1
archivo=""
dir="/home/centos/scripts/Node/data"
datos="datos"
datos2="datos2"
compara=""
inten=""
coord=""
titulo="$(date '+%y-%m-%d_%T')"

function salida {
  echo "Estoy en otro lugar"
	if [[ "$file" =~ 'BOSQUEREAL' ]];then
		echo $BOSQUEREALMESA
	fi
}

sudo inotifywait -m -r $ruta -e close_write|
    while read path action file; do
	min=$(date "+%M")
	echo $min
	echo $minActual
	actual=$(date "+%s")
	if [[ "$min" != "$minActual" ]]; then
		echo "Pase por aqui"
		minActual=$min
		#titulo=$(date "+%y-%m-%d_%T")
		#echo $titulo
		#echo $archivo > $dir/$titulo.txt
		sudo rm /home/centos/scripts/Node/data/datos2.txt
		touch /home/centos/scripts/Node/data/datos2.txt
		echo "" > $dir/$datos.txt
		#echo "" > $dir/$datos2.txt
		archivo=""	
	fi
        echo "El archivo es '$file' y la ruta es '$path' con la accion '$action'" # If so, do your thing here!
	estacion="$(echo $file | cut -d "2" -f 1)"
	if [[ "$estacion" =~ "IIUNAM" ]];then
		coord="-99.18187, 19.32982"
		filtro="SI"
		echo "IIUNAM"
	fi
	if [[ "$estacion" =~ "ARAGON" ]]; then
		coord="-99.079917, 19.465908"
		filtro="SI"
		echo "ARAGON"
	fi
	if [[ "$estacion" =~ "COAPA" ]]; then
		coord="-99.134678, 19.287818"
		filtro="SI"
		echo "COAPA"
	fi
	if [[ "$estacion" =~ "BOSQUEREAL" ]]; then
		coord="-99.283330, 19.436133"
		filtro="SI"
		echo "BOSQUE REAL"
	fi
        if [[ "$estacion" =~ "DOSRIOS" ]];then
                coord="-99.344314, 19.370004"
                echo "DOS RIOS"
        fi
        if [[ "$estacion" =~ "CUAJIMALPA" ]]; then
                coord="-99.291582, 19.355342"
		filtro="SI"
                echo "CUAJIMALPA"
        fi
        if [[ "$estacion" =~ "MADIN" ]]; then
                coord="-99.267414, 19.522665"
		filtro="SI"
                echo "MADIN"
        fi
        if [[ "$estacion" =~ "VHERMOSA" ]]; then
                coord="-99.276242, 19.372083"
		filtro="SI"
                echo "VISTA HERMOSA"
        fi
	        if [[ "$estacion" =~ "PREPA4" ]];then
                coord="-99.196129, 19.403589"
		filtro="SI"
                echo "PREPA 4"
        fi
        if [[ "$estacion" =~ "SACMEX" ]]; then
                coord="-99.137096, 19.425079"
		filtro="SI"
                echo "SACMEX"
        fi
        if [[ "$estacion" =~ "SISAL" ]]; then
                filtro="NA"
                echo "COAPA"
        fi
        if [[ "$estacion" =~ "CUERNAVACA" ]]; then
                filtro="NA"
                echo "BOSQUE REAL"
        fi
	archivo=$path$file
	if [[ "$filtro" =~ "SI" ]]; then
	while IFS= read -r line; do
		compara="`echo "$line" | cut -b 1,2,3`"
		if [[ "$compara" =~ "01:" ]]; then
			inten="`echo $line | cut -d ":" -f 2`"
			inten="`python -c "print $inten"`"
			echo=$inten
		fi
		if [[ "$compara" =~ "02:"  ]]; then
			acum="`echo $line | cut -d ":" -f 2`"
			acum="`python -c "print $acum"`"	
		fi
		if [[ "$compara" =~ "50:"  ]]; then
	        echo "{ "'"type"'": "'"Feature"'",
       		 "'"geometry"'": {"'"type"'": "'"Point"'", "'"coordinates"'": ["$coord"]},
      		 "'"properties"'": {
         	 "'"name"'": "'"'""$estacion""'"'",
         	 "'"value"'": "$inten"
       		 }
     		 }," >> $dir/$datos.txt                       
                fi
	done <"$archivo"
	fi
	if [[ "$estacion" =~ "IIUNAM" ]];then
                echo "IIUNAM;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "IIUNAM,$inten,$acum" > $dir/IIUNAM.txt
        fi
        if [[ "$estacion" =~ "ARAGON" ]]; then
	 	echo "ARAGON;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "ARAGON,$inten,$acum" > $dir/ARAGON.txt
        fi
        if [[ "$estacion" =~ "COAPA" ]]; then
 		echo "COAPA;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "COAPA,$inten,$acum" > $dir/COAPA.txt
        fi
        if [[ "$estacion" =~ "BOSQUEREAL" ]]; then
 		echo "BOSQUEREAL;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "BOSQUEREAL,$inten,$acum" > $dir/BOSQUEREAL.txt
        fi
        if [[ "$estacion" =~ "DOSRIOS" ]];then
 		echo "DOSRIOS;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "DOSRIOS,$inten,$acum" > $dir/DOSRIOS.txt
        fi
        if [[ "$estacion" =~ "CUAJIMALPA" ]]; then
 		echo "CUAJIMALPA;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "CUAJIMALPA,$inten,$acum" > $dir/CUAJIMALPA.txt
        fi
        if [[ "$estacion" =~ "MADIN" ]]; then
 		echo "MADIN;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "MADIN,$inten,$acum" > $dir/MADIN.TXT
        fi
        if [[ "$estacion" =~ "VHERMOSA" ]]; then
 		echo "VHERMOSA;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "VHERMOSA,$inten,$acum" > $dir/VHEMOSA.txt
        fi
       	if [[ "$estacion" =~ "PREPA4" ]];then
 		echo "PREPA4;$coord;$inten;$acum" >> $dir/$datos2.txt
		echo "PREPA4,$inten,$acum" > $dir/PREPA4.txt
        fi
        if [[ "$estacion" =~ "SACMEX" ]]; then
		 echo "SACMEX;$coord;$inten;$acum" >> $dir/$datos2.txt
		 echo "SACMEX,$inten,$acum" > $dir/SAMCEX.txt
        fi
    done
