#! /bin/bash
echo "Programa Estaciones"
ruta="/var/ftp/pub"
temporal=""
variable1=""
estacion=""
IIUNAM=""
IIUNAMMESA=""
COAPA=""
COAPAMESA=""
ARAGON=""
ARAGONMESA=""
BOSQUEREAL=""
BOSQUEREALMESA=""
minActual=$(date "+%M")
min=70
number=1
archivo=""
dir="/home/centos/scripts/Node/data"
datos="datos"
datos2=""
compara=""
inten=""
coord=""
titulo="$(date '+%y-%m-%d_%T')"

cd /home/centos/scripts/Node
sudo inotifywait -m -r $ruta -e close_write|
	while read path action file; do
	min=$(date "+%M")
	echo $min
	echo $minActual
	if [[ "$min" != "$minActual" ]]; then
		echo "Pase por aqui"
		minActual=$min
		#titulo=$(date "+%y-%m-%d_%T")
		#echo $titulo
		#echo $archivo > $dir/$titulo.txt
		#sudo rm -r output/datos.txt
		#touch output/datos.txt
		echo "" > $dir/$datos.txt
		archivo=""	
	fi
        echo "El archivo es '$file' y la ruta es '$path' con la accion '$action'" # If so, do your thing here!
	estacion="$(sudo echo $file | cut -d "2" -f 1)"
	if [[ "$estacion" =~ "IIUNAM" ]];then
		coord="-99.18187, 19.32982"
		filtro="SI"
		echo "IIUNAM"
	fi
	if [[ "$estacion" =~ "ARAGON" ]]; then
		coord="-99.079917, 19.465908"
		filtro="SI"
		echo "ARAGON"
	fi
	if [[ "$estacion" =~ "COAPA" ]]; then
		coord="-99.134678, 19.287818"
		filtro="SI"
		echo "COAPA"
	fi
	if [[ "$estacion" =~ "BOSQUEREAL" ]]; then
		coord="-99.283330, 19.436133"
		filtro="SI"
		echo "BOSQUE REAL"
	fi
        if [[ "$estacion" =~ "DOSRIOS" ]];then
                coord="-99.344314, 19.370004"
                echo "DOS RIOS"
        fi
        if [[ "$estacion" =~ "CUAJIMALPA" ]]; then
                coord="-99.291582, 19.355342"
		filtro="SI"
                echo "CUAJIMALPA"
        fi
        if [[ "$estacion" =~ "MADIN" ]]; then
                coord="-99.267414, 19.522665"
		filtro="SI"
                echo "MADIN"
        fi
        if [[ "$estacion" =~ "VHERMOSA" ]]; then
                coord="-99.276242, 19.372083"
		filtro="SI"
                echo "VISTA HERMOSA"
        fi
	        if [[ "$estacion" =~ "PREPA4" ]];then
                coord="-99.196129, 19.403589"
		filtro="SI"
                echo "PREPA 4"
        fi
        if [[ "$estacion" =~ "SACMEX" ]]; then
                coord="-99.137096, 19.425079"
		filtro="SI"
                echo "SACMEX"
        fi
        if [[ "$estacion" =~ "SISAL" ]]; then
                filtro="NA"
                echo "COAPA"
        fi
        if [[ "$estacion" =~ "CUERNAVACA" ]]; then
                filtro="NA"
                echo "BOSQUE REAL"
        fi
	archivo=$path$file
	if [[ "$filtro" =~ "SI" ]]; then
	while IFS= read -r line; do
		compara="`echo "$line" | cut -b 1,2,3`"
		if [[ "$compara" =~ "01:" ]]; then
			inten="`sudo echo $line | cut -d ":" -f 2`"
			inten="`python -c "print $inten"`"
			echo $inten
			       echo "{ "'"type"'": "'"Feature"'",
        "'"geometry"'": {"'"type"'": "'"Point"'", "'"coordinates"'": ["$coord"]},
        "'"properties"'": {
          "'"name"'": "'"'""$estacion""'"'",
          "'"value"'": "$inten"
        }
      }," >> $dir/$datos.txt

			#echo $line >> $dir/$datos.txt
		fi
		#if [[ "$compara" =~ "02:" ]]; then
		#	echo $line >> $dir/$datos.txt
		#fi
		#if [[ "$compara" =~ "22:" ]]; then
		#	echo $line >> $dir/$datos.txt
		#	echo "" >> $dir/$datos.txt
		#fi
	done <"$archivo"
	fi
	#datos2=$(<archivo)
        #echo $datos2 >> $dir/$datos.txt
    done
