#! /bin/bash
echo "Programa Estaciones"
ruta="/var/ftp/pub"
temporal=""
variable1=""
estacion=""
#IIUNAM=""
#IIUNAMMESA=""
#COAPA=""
#COAPAMESA=""
#ARAGON=""
#ARAGONMESA=""
#BOSQUEREAL=""
#BOSQUEREALMESA=""
minActual=$(date "+%M")
min=70  #minuto irreal que utilizo para no caer en la primera condicion if(minActul igual a min)
number=1
archivo=""
dir="/home/centos/scripts/Node/data"
dir2="/home/centos/scripts/Node/data/oh"
dir3="/var/www/html"
datos="datos"
datos2="datos2"
compara=""
inten=""
coord=""
aniomin="$(date '+%y%m')"
titulo="$(date '+%y-%m-%d_%T')"
parametro=""
control=""
inten=""
acum=""
inten2=""
acum2=""
visi=""
visi2=""
reflec=""
reflec2=""
gotas=""
gotas2=""
cine=""
cine2=""
fechaS=""
fechaS2=""
fechaC=""
horaS=""
horaS2=""
guion=""
estacion1=""
coma=";"

# Crea archivos de acumuladas 
touch /home/centos/scripts/Node/data/IIUNAMacum.txt
touch /home/centos/scripts/Node/data/SACMEXacum.txt
touch /home/centos/scripts/Node/data/MADINacum.txt
touch /home/centos/scripts/Node/data/PREPA4acum.txt
touch /home/centos/scripts/Node/data/DOSRIOSacum.txt
touch /home/centos/scripts/Node/data/CUAJIMALPAacum.txt
touch /home/centos/scripts/Node/data/BOSQUEREALacum.txt
touch /home/centos/scripts/Node/data/VHERMOSAacum.txt
touch /home/centos/scripts/Node/data/ARAGONacum.txt
touch /home/centos/scripts/Node/data/COAPAacum.txt
touch /home/centos/scripts/Node/data/CCHOTEacum.txt
touch /home/centos/scripts/Node/data/TLALNEacum.txt
touch /home/centos/scripts/Node/data/CCHVALLEJOacum.txt


#Le asigno permisos para que el usuario centos pueda leer los archivos
chown centos:centos /home/centos/scripts/Node/data/IIUNAMacum.txt
chown centos:centos /home/centos/scripts/Node/data/SACMEXacum.txt
chown centos:centos /home/centos/scripts/Node/data/MADINacum.txt
chown centos:centos /home/centos/scripts/Node/data/PREPA4acum.txt
chown centos:centos /home/centos/scripts/Node/data/DOSRIOSacum.txt
chown centos:centos /home/centos/scripts/Node/data/CUAJIMALPAacum.txt
chown centos:centos /home/centos/scripts/Node/data/BOSQUEREALacum.txt
chown centos:centos /home/centos/scripts/Node/data/VHERMOSAacum.txt
chown centos:centos /home/centos/scripts/Node/data/ARAGONacum.txt
chown centos:centos /home/centos/scripts/Node/data/COAPAacum.txt
chown centos:centos /home/centos/scripts/Node/data/CCHOTEacum.txt
chown centos:centos /home/centos/scripts/Node/data/TLALNEacum.txt
chown centos:centos /home/centos/scripts/Node/data/CCHVALLEJOacum.txt


#Termina inizalización de archivos, podria corre en un codigo diferente
#y dejar en otro solo la rutina de del while


#Todo el programa es un while que abarca todo
sudo inotifywait -m -r $ruta -e close_write|
    while read path action file; do
        aniomin="$(date '+%y%m')"
        min=$(date "+%M")  #Cada que llega un archivo veo que minuto es
        fecha=$(date "+%D_%H:%M:%S")  #Pido la fecha completa, %D dd/mm/aa %H hora %M min %S seg
        echo $min
        echo $minActual 
        actual=$(date "+%s") #tiempo actual en milisegundos, sirve para restar valores
        if [[ "$min" != "$minActual" ]]; then  #Ciclo que se utiliza para reinicialar variables cada que cambie el minuto
                echo "Ha cambiado de minuto!!"
                minActual=$min #Asigno minutoActual para la comparación
                echo "" > $dir/$datos2.txt #Inicializa archivo para crear mapa de precipitación
                echo "" > $dir/$datos.txt #Inicializo el archivo para crear pines en el mapa
                archivo=""  # Inicializo variable archivo
        fi
        echo "El archivo es '$file' y la ruta es '$path' con la accion '$action'" # If so, do your thing here!
        estacion="$(echo $file | cut -d "_" -f 1)" #Separo el nombre del archivo por guiones
        if [[ $estacion == IIUNAM* ]];then
                coord="-99.18187, 19.32982"
                filtro="SI"
                estacion="IIUNAM"
                estacion2="iiunam"
                mapa="SI"
                echo $estacion
        
        elif [[ $estacion == ARAGON* ]]; then
                coord="-99.079917, 19.465908"
                filtro="SI"
                estacion="ARAGON"
                estacion2="aragon"
                mapa="SI"
                echo "ARAGON"
        
        elif [[ $estacion == COAPA* ]]; then
                coord="-99.134678, 19.287818"
                filtro="SI"
                estacion="COAPA"
                estacion2="coapa"
                mapa="SI"
                echo "COAPA"
        
        elif [[ $estacion == BOSQUEREAL* ]]; then
                coord="-99.283330, 19.436133"
                filtro="SI"
                estacion="BOSQUEREAL"
                estacion2="bosquereal"
                mapa="SI"
                echo "BOSQUE REAL"
        
        elif [[ $estacion == DOSRIOS* ]];then
                coord="-99.344314, 19.370004"
                filtro="SI"
                estacion="DOSRIOS"
                estacion2="dosrios"
                mapa="SI"
                echo "DOS RIOS"
        
        elif [[ $estacion == CUAJIMALPA* ]]; then
                coord="-99.291582, 19.355342"
                filtro="SI"
                estacion2="cuajimalpa"
                estacion="CUAJIMALPA"
                mapa="SI"
                echo "CUAJIMALPA"
        
        elif [[ $estacion == MADIN* ]]; then
                coord="-99.267414, 19.522665"
                filtro="SI"
                estacion="MADIN"
                estacion2="madin"
                mapa="SI"
                echo "MADIN"
        
        elif [[ $estacion == VHERMOSA* ]]; then
                coord="-99.276242, 19.372083"
                filtro="SI"
                estacion="VHERMOSA"
                estacion2="vhermosa"
                mapa="SI"
                echo "VISTA HERMOSA"
        
        elif [[ $estacion == PREPA4* ]];then
                coord="-99.196129, 19.403589"
                filtro="SI"
                estacion="PREPA4"
                mapa="SI"
                echo "PREPA 4"
        
        elif [[ $estacion == SACMEX* ]]; then
                coord="-99.137096, 19.425079"
                filtro="SI"
                estacion="SACMEX"
                mapa="SI"
                echo "SACMEX"
        
        elif [[ $estacion == TLALNE* ]]; then
                coord="-99.194856, 19.538833"
                filtro="SI"
                estacion="TLALNE"
                mapa="SI"
                echo "TLALNE"
        
        elif [[ $estacion == CCHOTE* ]]; then
                coord="-99.059703, 19.383573"
                filtro="SI"
                estacion="CCHOTE"
                mapa="SI"
                echo "CCHOTE"
        
        elif [[ $estacion == CCHVALLEJO* ]]; then
                coord="-99.140496, 19.482562"
                filtro="SI"
                estacion="CCHVALLEJO"
                mapa="SI"
                echo "CCH-VALLEJO"
        
        elif [[ $estacion == SISAL* ]]; then
                filtro="NA"
                coord=""
                estacion=""
                mapa="NO"
                echo "SISAL"
        
        elif [[ $estacion == CUERNAVACA* ]]; then
                filtro="NA"
                estacion=""
                coord=""
                mapa="NO"
                echo "CUERNAVACA"

        else
                #Borrar variables para que no caer en problmea
                filtro="NA"
                estacion=""
                coord=""
                mapa="NO"
                echo "El archivo "$file" no tiene autorizacion"
                echo "Ninguna estación Conocida"
        fi
        if [[ "$filtro" == "SI" ]]; then
                if [[ $file == *.oh  ]]; then
                    echo "Archivo comprimido esta comprimido"
                    gunzip -c < $path$file | while read line do
                        #echo "Entre a CCHOTE"
                        compara="`echo $line | cut -b 1,2`"
                        #echo $compara
                        if [[ $compara == "01" ]]; then
                                echo "Pase por aqui en cch"
                                inten2="`echo $line | cut -d ":" -f 2`"
                                inten2="`python -c "print $inten2"`"
                                echo $inten2
                        fi
                        if [[ $compara == "02" ]]; then
                                echo $line
                                acum2="`echo $line | cut -d ":" -f 2`"
                                acum2="`python -c "print $acum2"`"
                                echo $acum2
                        fi


                        if [[ $compara == "07" ]]; then
                                echo $line
                                reflec2="`echo $line | cut -d ":" -f 2`"
                                reflec2="`python -c "print $reflec2"`"
                                echo $reflec2
                        fi

                        if [[ $compara == "08" ]]; then
                                echo $line
                                visi2="`echo $line | cut -d ":" -f 2`"
                                visi2="`python -c "print $visi2"`"
                                echo $visi2
                        fi


                        if [[ $compara == "11" ]]; then
                                echo $line
                                gotas2="`echo $line | cut -d ":" -f 2`"
                                gotas2="`python -c "print $gotas2"`"
                                echo $gotas2
                        fi


                        if [[ $compara == "20" ]]; then
                                hora="`echo $line | cut -d ":" -f 2`"
                                min="`echo $line | cut -d ":" -f 3`"
                                #seg="`echo $line | cut -d ":" -f 4`"
                                #seg=${seg:0:2}
                                p=":"
                                horaS2=$hora$p$min
                                #horaS="`python -c "print $horaS"`"
                                echo $horaS2
                        fi

                        if [[ $compara == "21" ]]; then
                                fechaS="`echo $line | cut -d ":" -f 2`"
                                dia="`echo $fechaS | cut -d "." -f 1`"
                                mes="`echo $fechaS | cut -d "." -f 2`"
                                anio="`echo $fechaS | cut -d "." -f 3`"
                                anio=${anio:0:4}
                                 d="/"
                                d2="."
                                uno=1
                                mesp="$((mes - uno))"
                                fechaS2=$anio$d$mesp$d$dia
                                fechap=$anio$d2$mes$d2$dia
                                #fechaS2="`python -c "print $fechaS"`"
                                echo $fechaS2
                        fi


                        if [[ $compara == "34" ]]; then
                                echo $line
                                cine2="`echo $line | cut -d ":" -f 2`"
                                cine2="`python -c "print $cine2"`"
                                echo $cine2
                        fi


                        if [[ $compara == "50" ]]; then
                        echo "{ "'"type"'": "'"Feature"'",
                        "'"geometry"'": {"'"type"'": "'"Point"'", "'"coordinates"'": ["$coord"]},
                        "'"properties"'": {
                        "'"name"'": "'"'""$estacion""'"'",
                        "'"value"'": "$inten2"
                        }
                        }," >> $dir/$datos.txt

                        touch $dir2/$estacion.csv
                        echo  $estacion$coma$fechaC$coma$horaS$coma$inten$coma$acum$coma$reflec$coma$visi$coma$gotas$coma$cine >> $dir2/estacion.csv
                        echo  $estacion$coma$fechap$coma$horaS$coma$inten$coma$acum > $dir2/a$estacion.csv
                        cp  $dir2/a$estacion.csv $dir3/$estacion/a$estacion$aniomes.csv
                        mv $dir3/$estacion/a$estacion$aniomes.csv $dir3/$estacion/dbm$estacion$aniomes.csv
                        chown apache:centos $dir3/$estacion2/dbm$estacion$anio$mes.csv
                        gzip -c $dir2/$estacion.csv > $dir3/$estacion2/$estacion.gz
                        mv $dir3/$estacion2/$estacion.gz $dir3/$estacion2/dbp$estacion$aniomes.gz
                        chown apache:centos $dir3/$estacion2/dbp$estacion$aniomes.gz
                        echo "$estacion;$coord;$inten;$acum" >> $dir/$datos2.txt
                        echo "$estacion,$inten,$acum" > $dir/$estacion.txt
                        echo "$actual,$estacion,$acum,$inten,$fecha" >> $dir/$estacionacum.txt

                        fi
                    done
                

                elif [[ $file == *.txt  ]]; then
                    echo "Archivo no esta comprimido"
                    while IFS= read -r line; do
                        compara="`echo "$line" | cut -b 1,2`"

                        if [[ $compara == "01" ]]; then
                        inten="`echo $line | cut -d ":" -f 2`"
                        inten="`python -c "print $inten"`"
                        echo $inten
                        fi

                        if [[ $compara == "02" ]]; then
                        acum="`echo $line | cut -d ":" -f 2`"
                        acum="`python -c "print $acum"`"
                        echo $acum
                        fi

                        if [[ $compara == "07" ]]; then
                                reflec="`echo $line | cut -d ":" -f 2`"
                                reflec="`python -c "print $reflec"`"
                                echo $reflec
                        fi

                        if [[ $compara == "08" ]]; then
                                visi="`echo $line | cut -d ":" -f 2`"
                                visi="`python -c "print $visi"`"
                                echo $visi
                        fi

                        if [[ $compara == "11" ]]; then
                                gotas="`echo $line | cut -d ":" -f 2`"
                                gotas="`python -c "print $gotas"`"
                                echo $gotas
                        fi

                        if [[ $compara == "20" ]]; then
                                hora="`echo $line | cut -d ":" -f 2`"
                                min="`echo $line | cut -d ":" -f 3`"
                                #seg="`echo $line | cut -d ":" -f 4`"
                                #seg=${seg:0:2}
                                p=":"
                                horaS=$hora$p$min
                                #horaS="`python -c "print $horaS"`"
                                echo $horaS
                        fi

                        if [[ $compara == "21" ]]; then
                                fechaS="`echo $line | cut -d ":" -f 2`"
                                dia="`echo $fechaS | cut -d "." -f 1`"
                                mes="`echo $fechaS | cut -d "." -f 2`"
                                anio="`echo $fechaS | cut -d "." -f 3`"
                                anio=${anio:0:4}
                                d="/"
                                d2="."
                                uno=1
                                mesp="$((mes - uno))"
                                fechaC=$anio$d$mesp$d$dia
                                fechap=$anio$d2$mes$d2$dia
                                #fechaS2="`python -c "print $fechaS"`"
                                echo $fechaC
                        fi

                        if [[ $compara == "34" ]]; then
                                cine="`echo $line | cut -d ":" -f 2`"
                                cine="`python -c "print $cine"`"
                                echo $cine
                        fi

                        if [[ $compara = "50"  ]]; then
                        echo "{ "'"type"'": "'"Feature"'",
                        "'"geometry"'": {"'"type"'": "'"Point"'", "'"coordinates"'": ["$coord"]},
                        "'"properties"'": {
                        "'"name"'": "'"'""$estacion""'"'",
                        "'"value"'": "$inten"
                        }
                        }," >> $dir/$datos.txt


                        touch $dir2/$estacion.csv
                        echo  $estacion$coma$fechaC$coma$horaS$coma$inten$coma$acum$coma$reflec$coma$visi$coma$gotas$coma$cine >> $dir2/estacion.csv
                        echo  $estacion$coma$fechap$coma$horaS$coma$inten$coma$acum > $dir2/a$estacion.csv
                        cp  $dir2/a$estacion.csv $dir3/$estacion/a$estacion$aniomes.csv
                        mv $dir3/$estacion/a$estacion$aniomes.csv $dir3/$estacion/dbm$estacion$aniomes.csv
                        chown apache:centos $dir3/$estacion2/dbm$estacion$anio$mes.csv
                        gzip -c $dir2/$estacion.csv > $dir3/$estacion2/$estacion.gz
                        mv $dir3/$estacion2/$estacion.gz $dir3/$estacion2/dbp$estacion$aniomes.gz
                        chown apache:centos $dir3/$estacion2/dbp$estacion$aniomes.gz
                        echo "$estacion;$coord;$inten;$acum" >> $dir/$datos2.txt
                        echo "$estacion,$inten,$acum" > $dir/$estacion.txt
                        echo "$actual,$estacion,$acum,$inten,$fecha" >> $dir/$estacionacum.txt

                        fi
                    done < $path$file
                else
                echo "El archivo no es .oh ni .txt"
                fi
        fi
    done

